[#2602] [JSDoc] Add missing documentation for adaptive-expressions/builtinFuntions files 1/10
microsoft/botbuilder-js pull request #2843
Opened 2020-10-01 18:36 UTC by denscollo

Addresses #2602

## Description
This PR adds the missing documentation in [adaptive-expressions/builtinFunctions/](https://github.com/microsoft/botbuilder-js/tree/main/libraries/adaptive-expressions/src/builtinFunctions) files.
Some documentation is ported and adapted from [botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet)

## Specific Changes
- Added JSDoc comments in all public methods.
- Added `@private` attribute to private methods.
- Fixes linter spacing warnings.

## Testing
The following image shows the ESLint Report with no JSDoc errors.
![image](https://user-images.githubusercontent.com/64803884/94719157-2c7f1300-0329-11eb-8f0c-0b674cc65c40.png)

2020-10-02 02:05 UTC, chrimc62 commented on libraries/adaptive-expressions/src/builtinFunctions/addToTime.ts
> +                error = `${ expression } should contain an ISO format timestamp, a time interval integer, a string unit of time and an optional output format string.`;
>${ expression } [](start = 25, length = 15)

I don't think this is our coding style.

2020-10-02 02:05 UTC, chrimc62 approved these changes
:shipit:

2020-10-06 19:31 UTC, joshgummersall requested changes
In an effort to improve generated docs, properly linking types with `[link text](xref:uid)` would be really helpful.

See more details [here](https://github.com/microsoft/botbuilder-js/pull/2838#discussion_r499724516) and [here](https://github.com/microsoft/botbuilder-js/pull/2838#discussion_r499748705).

2020-10-14 23:09 UTC, joshgummersall approved these changes

2020-10-16 17:02 UTC, merged