Filter continueConversation events when logging
microsoft/botbuilder-js pull request #2903
Opened 2020-10-14 22:47 UTC by joshgummersall

Fixes #2805

This PR also includes a small test refactoring to use `sinon` for mocking and verifying error handling. It's a more natural way to set up expectations and verify them without patching methods. It was a bit of bikeshedding, but it should serve as a useful example for future testing scenarios.

2020-10-14 22:47 UTC, joshgummersall commented on libraries/botbuilder-core/tests/transcriptMiddleware.test.js
> +    describe("'s error handling", function () {
For reference, this is the major test refactor portion.

2020-10-19 21:18 UTC, stevengum commented on libraries/botbuilder-core/src/transcriptLogger.ts
> +            async (ctx: TurnContext, activities: Partial<Activity>[], next: () => Promise<ResourceResponse[]>) => {
These random `next2` have caused me random bits of anguish, thanks for changing the name!

2020-10-19 23:14 UTC, stevengum requested changes
For the actual values of constants, enums, etc we do stay aligned with what's used in C#/other languages. Once the .NET PR lands the ActivityEventNames enum in JS should match. Other than that, the PR looks solid!

As a general rule, if it's a value that might be serialized and could be shared across languages, it should be aligned across all languages.

2020-10-19 23:18 UTC, joshgummersall commented on libraries/botframework-schema/src/index.ts
> +  CreateConversation = 'createConversation'
Good catch - that makes sense.

2020-10-20 16:13 UTC, stevengum approved these changes
LGTM!

2020-10-20 16:33 UTC, merged